GET http://localhost:3001/personnels

###

POST http://localhost:3001/personnels/new
Content-Type: application/json

{
    "ID":"D202dad",
	"CIN":202444,
	"FirstName":"bruh",
    "LastName":"momento",
    "Job": "Supervisor",
    "Password": "azer1Maa"
}

###

DELETE http://localhost:3001/personnel/delete/6609dadad4ddda52aa3da2a21a3d0f8d

###
 GET http://localhost:3001/personnel/660947a52aa3a2a21a3d0f8d

###
 
 PUT http://localhost:3001/personnel/update/660947a52aa3a2a21a3d0f8d 
 Content-Type: application/json

 {
    "ID":"D2024@ksour",
	"CIN":14,
	"FirstName":"fhedi",
    "LastName":"tddd" ,
    "Job": "Headmastaaaer",
    "Password":"0da0da0" 
}

###

GET http://localhost:3001/alumnis

###

POST http://localhost:3001/alumni/new
Content-Type: application/json

{
	"FirstName":"Mohamed",
    "LastName":"Magherbi",
    "Spec": "génie LOG",
    "Age": 12
}

###
DELETE http://localhost:3001/alumni/delete/660952baafb061b018292a1f

###
 GET http://localhost:3001/alumni/660952c9afb061b018292a24

###
 PUT http://localhost:3001/alumni/update/660952c9afb061b018292a24 
 Content-Type: application/json

 {
    
	"FirstName":"fhedi",
    "LastName":"tddd" ,
    "Age":18,
    "Spec":"Génie IND" 
}

###
POST http://localhost:3001/personnels/login
Content-Type: application/json

{

    "ID":"D2204",
    "password":"flyinraijin"
}

###

POST http://localhost:3001/teachers/new
Content-Type: application/json

{
    "_id":"660a9b652a3130b87e2ae0df",
    "subject":"Math"
}
###
GET http://localhost:3001/teachers/
###
GET http://localhost:3001/teachers/660c08ecb8b0a80034d21e56