GET http://localhost:3001/personnels

###

POST http://localhost:3001/personnels/new
Content-Type: application/json

{
    "ID":"dqdqd",
	"CIN":2412122424,
	"FirstName":"bruh",
    "LastName":"momento",
    "Job": "Supervisor",
    "Password": "azeraea1Maa"
}

###

DELETE http://localhost:3001/personnel/delete/6609dadad4ddda52aa3da2a21a3d0f8d

###
 GET http://localhost:3001/personnel/660947a52aa3a2a21a3d0f8d

###
 
 PUT http://localhost:3001/personnel/update/660947a52aa3a2a21a3d0f8d 
 Content-Type: application/json

 {
    "ID":"D2024@ksour",
	"CIN":14,
	"FirstName":"fhedi",
    "LastName":"tddd" ,
    "Job": "Headmastaaaer",
    "Password":"0da0da0" 
}

###

GET http://localhost:3001/alumnis/

###

POST http://localhost:3001/alumnis/new
Content-Type: application/json

{
	"FirstName":"Mohamed",
    "LastName":"Magherbi",
    "Spec": "génie LOG",
    "Age": 12
}

###
DELETE http://localhost:3001/alumnis/delete/660952baafb061b018292a1f

###
 GET http://localhost:3001/alumnis/660952c9afb061b018292a24

###
 PUT http://localhost:3001/alumnis/update/660952c9afb061b018292a24 
 Content-Type: application/json

 {
    
	"FirstName":"fhedi",
    "LastName":"tddd" ,
    "Age":18,
    "Spec":"Génie IND" 
}

###
POST http://localhost:3001/personnels/login
Content-Type: application/json

{

    "ID":"D2204",
    "password":"flyinraijin"
}

###

POST http://localhost:3001/teachers/new
Content-Type: application/json

{
    "_id":"660a9b652a3130b87e2ae0df",
    "spec":"Math"
}
###
GET http://localhost:3001/teachers/
###
GET http://localhost:3001/teachers/660c08ecb8b0a80034d21e56
###
GET http://localhost:3001/timetables/
###
POST http://localhost:3001/timetables/new/
Content-Type: application/json

{
    "_id":"660a9b652a3130b87e2ae0df",
    "subject":"660d5c4e336e020b36759f7b",
    "class":"660d5d5b336e020b36759f7f"
}
###
PUT http://localhost:3001/timetables/update/660d5d9571b0076105a301b0
Content-Type: application/json

{
    "hours":2,
    "timetable":[
    ["s1", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", "s3", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", ""]
]
}
###

GET http://localhost:3001/classes/
###
POST http://localhost:3001/classes/new/
Content-Type: application/json

{
    "ClassName":"3 GL"
}
###
PUT http://localhost:3001/classes/updateAlumnis/660d5c4e336e020b36759f7b
###
GET http://localhost:3001/subjects/
###
POST http://localhost:3001/subjects/new
Content-Type: application/json

{
    "SubjectName":"English",
    "Coef":4,
    "Coefdc":1.5,
    "Coefds":2
}
###
GET http://localhost:3001/grades/
###
POST http://localhost:3001/grades/new
Content-Type: application/json

{
    "alumni":"660953103da6f725818eef95",
    "teacher":"660c08ecb8b0a80034d21e56",
    "subject":"66100003e58e339373609abe",
    "tp":19,
    "ds":15
}
###
PUT http://localhost:3001/grades/update/660ffd8745d7cae4ccfcc867
Content-Type: application/json

{
    "tp":10
}
###
GET http://localhost:3001/teachings/
###
POST http://localhost:3001/teachings/new
Content-Type: application/json

{
    "class":"660d5c4e336e020b36759f7b",
    "teacher":"660c08ecb8b0a80034d21e56",
    "subject":"66100003e58e339373609abe"
}
###
GET http://localhost:3001/registres/
###
POST http://localhost:3001/registres/new
Content-Type: application/json

{
    "alumni":"660953103da6f725818eef95",
    "teaching":"661159491e75c1d7cfc111d6"
}
###
PUT http://localhost:3001/registres/updateUp/66115a0db0db072dffd64957
###
PUT http://localhost:3001/registres/updateDown/66115a0db0db072dffd64957
